/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface I18nextWcStencil {
    }
}
declare global {
    interface HTMLI18nextWcStencilElement extends Components.I18nextWcStencil, HTMLStencilElement {
    }
    var HTMLI18nextWcStencilElement: {
        prototype: HTMLI18nextWcStencilElement;
        new (): HTMLI18nextWcStencilElement;
    };
    interface HTMLElementTagNameMap {
        "i18next-wc-stencil": HTMLI18nextWcStencilElement;
    }
}
declare namespace LocalJSX {
    interface I18nextWcStencil {
    }
    interface IntrinsicElements {
        "i18next-wc-stencil": I18nextWcStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i18next-wc-stencil": LocalJSX.I18nextWcStencil & JSXBase.HTMLAttributes<HTMLI18nextWcStencilElement>;
        }
    }
}
